#include<bits/stdc++.h>
using namespace std;
long long a[2000005],b[2000005],kk[2000005];
bool d[2000005];
int main()
{
    ios_base::sync_with_stdio();
    cin.tie();cout.tie();
    freopen("CAU3.inp","r",stdin);
    freopen("CAU3.out","w",stdout);
    long long n,m,i,j,dem=0,ab,g,kt1=0,kt2=0,k,x;
    for(i=2;i*i<=1000100;i++)
    {
        if(d[i]==false)
        {
            for(j=i*i;j<=1000100;j=j+i)
            {
                d[j]=true;
            }
        }
    }
    d[1]=true;
    cin>>n>>m;
    for(i=1;i<=n;i++)
    {
        cin>>a[i];
        if(d[a[i]]==false)
        {
            kt1++;
        }
    }
    for(i=1;i<=m;i++)
    {
        cin>>b[i];
        if(d[b[i]]==false)
        {
            kt2++;
        }
    }
    if(n<=1000&&m<=1000)
    {
        dem=0;
        for(i=1;i<=n;i++)
        {
            ab=0;
            for(j=1;j<=m;j++)
            {
                if(__gcd(a[i],b[j])!=1)
                {
                    ab=1;
                    break;
                }
            }
            if(ab==0)
            {
                dem++;
            }
        }
        cout<<dem;
    }
    else
    {
        if(kt1==n&&kt2==m)
    {
        dem=0;
        for(i=1;i<=m;i++)
        {
            kk[b[i]]++;
        }
        for(i=1;i<=n;i++)
        {
            if(kk[a[i]]==0)
            {
                dem++;
            }
        }
        cout<<dem;
    }
    else
    {
        dem=0;
    for(i=1;i<=m;i++)
    {
        x=b[i];
        for(j=2;j*j<=b[i];j++)
        {
            if(x%j==0)
            {
                while(x%j==0)
                {
                    kk[j]++;
                    x=x/j;
                }
            }
        }
        if(x>1)
        {
            kk[x]++;
        }
    }
    for(i=1;i<=n;i++)
    {
        x=a[i];
        ab=0;
        for(j=2;j*j<=a[i];j++)
        {
            if(x%j==0)
            {
                if(kk[j]>0)
                {
                    ab=1;
                    break;
                }
                else
                {
                    while(x%j==0)
                    {
                        x=x/j;
                    }
                }
            }
        }
        if(x>1&&kk[x]>0)
        {
            ab=1;
        }
        if(ab==0)
        {
            dem++;
        }
    }
    cout<<dem;
    }
    }
}
